# Default values for indexer-tools.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/vincenttaglia/indexer-tools
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Production or Development
env: production

config: 
  VITE_GRAPH_API_KEY: "3bab348a7c385b1870039eb890fd0a5f" # Default key provided with repo is limited to $25/mo in queries and will likely hit the limit early in the month.
  DEFAULT_ACCOUNTS: 
    - address: "0x1b92e4cba0f82c85c1298af861247849988c788c" # make sure the address don't have capital letters
      name: "vincenttaglia-indexer.eth"
      active: true
      chain: "arbitrum-one"
      agentConnect: false
      agentEndpoint: "https://localhost:8000" # use localhost port-forward to your http://graph-network-indexer-agent:8000
      poiQuery: false
      poiQueryEndpoint: "https://public.your-domain.com/graphql" # your public poiQuery endpoint
  DEFAULT_RPC_MAINNET: "https://mainnet.infura.io/v3/659344f230804542a4e653f875172105"
  DEFAULT_RPC_ARBITRUM: "https://arb-mainnet.g.alchemy.com/v2/er8LBcXpoFwlV8xJee-WXFbFG_M8L4JK"
  DEFAULT_RPC_SEPOLIA: "https://ethereum-sepolia.rpc.subquery.network/public"
  DEFAULT_RPC_ARBITRUM_SEPOLIA: "https://arbitrum-sepolia.infura.io/v3/abb8c61191474a8aa840a892be991119"
  DEFAULT_SUBGRAPH_MAINNET: "https://gateway.thegraph.com/api/[api-key]/subgraphs/id/9Co7EQe5PgW3ugCUJrJgRv4u9zdEuDJf8NvMWftNsBH8"
  DEFAULT_SUBGRAPH_ARBITRUM: "https://gateway.thegraph.com/api/[api-key]/subgraphs/id/DZz4kDTdmzWLWsV373w2bSmoar3umKKH9y82SUKr5qmp"
  DEFAULT_SUBGRAPH_SEPOLIA: "https://gateway.thegraph.com/api/[api-key]/subgraphs/id/8pVKDwHniAz87CHEQsiz2wgFXGZXrbMDkrxgauVVfMJC"
  DEFAULT_SUBGRAPH_ARBITRUM_SEPOLIA: "https://gateway.thegraph.com/api/[api-key]/subgraphs/id/3xQHhMudr1oh69ut36G2mbzpYmYxwqCeU6wwqyCDCnqV"
  DEFAULT_QOS_SUBGRAPH: "https://gateway.thegraph.com/api/[api-key]/subgraphs/id/Dtr9rETvwokot4BSXaD5tECanXfqfJKcvHuaaEgPDD2D"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: ""
  annotations: {}
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # cert-manager.io/subject-organizations: "Chain-Insights"
  hosts:
    - host: indexer-tools.your-domain.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
   - secretName: indexer-tools-tls
     hosts:
       - indexer-tools.your-domaine.com

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: 
- name: config-volume
  configMap:
    name: indexer-tools-config
- name: config-dist
  configMap:
    name: indexer-tools-config

# Additional volumeMounts on the output Deployment definition.
volumeMounts: 
  - name: config-volume
    mountPath: /app/public/indexer-tools-config.json
    subPath: indexer-tools-config.json
  - name: config-dist
    mountPath: /app/dist/indexer-tools-config.json
    subPath: indexer-tools-config.json

nodeSelector: {}

tolerations: []

affinity: {}
