#!/bin/sh

JSON_STRING="{
  \"DEFAULT_ACCOUNTS\": ${DEFAULT_ACCOUNTS:-\"\"},
  \"DEFAULT_RPC_MAINNET\": \"${DEFAULT_RPC_MAINNET}\",
  \"DEFAULT_RPC_ARBITRUM\": \"${DEFAULT_RPC_ARBITRUM}\",
  \"DEFAULT_RPC_SEPOLIA\": \"${DEFAULT_RPC_SEPOLIA}\",
  \"DEFAULT_RPC_ARBITRUM_SEPOLIA\": \"${DEFAULT_RPC_ARBITRUM_SEPOLIA}\",
  \"DEFAULT_SUBGRAPH_MAINNET\": \"${DEFAULT_SUBGRAPH_MAINNET}\",
  \"DEFAULT_SUBGRAPH_ARBITRUM\": \"${DEFAULT_SUBGRAPH_ARBITRUM}\",
  \"DEFAULT_SUBGRAPH_SEPOLIA\": \"${DEFAULT_SUBGRAPH_SEPOLIA}\",
  \"DEFAULT_SUBGRAPH_ARBITRUM_SEPOLIA\": \"${DEFAULT_SUBGRAPH_ARBITRUM_SEPOLIA}\",
  \"DEFAULT_QOS_SUBGRAPH\": \"${DEFAULT_QOS_SUBGRAPH}\",
  \"GRAPH_API_KEY\": \"${GRAPH_API_KEY}\"
}"

echo $JSON_STRING > /app/public/indexer-tools-config.json

echo $JSON_STRING > /app/dist/indexer-tools-config.json

exec "$@"